test:karma:
  stage: test
  image: circleci/node:12-browsers
  script:
    - npm ci
    - npx ng test --progress false --watch false

lint:
  stage: test
  image: node:12-alpine
  script:
    - npm ci
    - npx ng lint

build:
  image: node:12-alpine
  stage: build
  script:
    - npm ci
    - npx ng build --prod
  artifacts:
    paths:
      - dist/
    expire_in: 24 hours
  cache:
    key: build
    paths:
      - $HOME/.npm/

deploy:
  stage: deploy
  image: sarunint/firebase-tools:latest
  only:
    - master
  dependencies:
    - build
  script:
    - firebase deploy --only hosting --token "$FIREBASE_TOKEN"

stages:
  - test
  - build
  - deploy
